version: '3.1'

services:
  mongo:
    container_name: mongodb_service
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cbellodev92
    ports:
      - 27017:27017
    volumes:
      - /home/camilo/docker/mongo/data:/data/db
